<h3 align="center">Huge Stock Market Dataset</h3> 

* 출처 : https://www.kaggle.com/kratisaxena/stock-market-technical-indicators-visualization
* 목저 : 분석 및 학습

In [13]:
import numpy as np
import pandas as pd

import os
# os module 요약
#    :  for interacting with the operating system
#    :  portable way
# >> * os./* and./* os.path modules를 중심으로 파일 시스템을 interacting하기 위한 주요 Function들이 있음.
# >> Examples)__ 'os.name', 'os.getwd()', 'os.error', 'os.popen()', 'os.close', os.rename

import random
import copy
import matplotlib.pyplot as plt
import pandas

In [16]:
os.getcwd()
# os.chdir('./input/Data/Stocks')
list = os.listdir()
number_files = len(list)
print(number_files)

7195


- [x for x in os.listdir() if x.endswith('.txt') and os.path.getsize(os.path.join('',x)) > 0]
    * x for x : 
        - Ex)__ [x*x for x in range(10)] >> [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
    * x for x with if
        - Ex)__ primes = [x for x in range(2, 50) if x not in noprimes] 이는 하단의 loop와 같다.
                       ~ primes = []
                            for x in range(2,50):
                               if x not in noprimes:
                                   primes.append(x) 
- endswitch() 
    * string.endswith(value, start, end)
        : 지정한 'value'로 'string'이 마침 된다면 'True'를 반환.  
- os.path.getsize()    
    * Print the size (in bytes) 
- os.path.join()    
    * Ex)__ print(os.path.join(path, "User/Public/", "Documents", "")) ~ /home/User/Public/Documents/
    


######  <font color='blue'>공파일이 아닌 txt파일 중 8개 파일을 random으로 호출</font>

In [17]:
filenames = random.sample([x for x in os.listdir() if x.endswith('.txt') 
                           and os.path.getsize(os.path.join('',x)) > 0], 8)
print(filenames)

['thc.us.txt', 'ssw_g.us.txt', 'acta.us.txt', 'uza.us.txt', 'rmp.us.txt', 'cio.us.txt', 'agm.us.txt', 'sdvy.us.txt']

######  <font color='blue'>Data_frame 생성</font>

In [18]:
data = []
for filename in filenames:
    df = pd.read_csv(os.path.join('',filename), sep=',')
    label, _, _ = filename.split(sep='.')
    df['Label'] = label
    df['Date'] = pd.to_datetime(df['Date'])

    data.append(df)

In [19]:
data[0].tail()

           Date   Open   High    Low  Close   Volume  OpenInt Label
9037 2017-11-06  13.11  13.13  12.49  12.65  5909711        0   thc
9038 2017-11-07  13.28  13.88  12.78  13.21  7041401        0   thc
9039 2017-11-08  13.22  13.68  12.91  13.63  3133643        0   thc
9040 2017-11-09  13.18  13.54  13.04  13.50  1942268        0   thc
9041 2017-11-10  13.50  13.96  13.50  13.82  3128427        0   thc

In [20]:
print(len(data))

8

##### <font color='green'>객체복사의 종류</font>
###### Shallow copy / Deep copy
* 단순 객체복제 :
        변수만 복사하기 때문에 바라보는 객체는 당연히 동일 반면, 두개의 변수 중 하나만 변경되어도 나머지 하나가 동일하게 수정되는 현상이 발생
* Shallow copy : 
    immutable한 경우는 제외하고, 리스트의 item 내부의 객체가 동일한 객체라면, mutable한 리스트를 수정할때는 둘다 값이 변경됨
* Deep copy : 
    내부의 객체들까지 모두 새롭게 카피
    
##### <font color='red'>기술적 지표 정리</font>
* RSI, Volume (plain), Bollinger Bands, Aroon, Price Volume Trend, acceleration bands _

##### <font color='green'>객체복사의 종류</font>
###### Shallow copy / Deep copy
* 단순 객체복제 :
        변수만 복사하기 때문에 바라보는 객체는 당연히 동일 반면, 두개의 변수 중 하나만 변경되어도 나머지 하나가 동일하게 수정되는 현상이 발생
* Shallow copy : 
    immutable한 경우는 제외하고, 리스트의 item 내부의 객체가 동일한 객체라면, mutable한 리스트를 수정할때는 둘다 값이 변경됨
* Deep copy : 
    내부의 객체들까지 모두 새롭게 카피
    
##### <font color='red'>기술적 지표 정리</font>
* RSI, Volume (plain), Bollinger Bands, Aroon, Price Volume Trend, acceleration bands _1
* Stochastic, Chaikin Money Flow, Parabolic SAR, Rate of Change, Volume weighted average Price, momentum _2
* Commodity Channel Index, On Balance Volume, Keltner Channels, Triple Exponential Moving _3 
* Average Normalized Averager True Range ,directional movement indicators _4
* MACD, Money flowindex, Ichimoku, William %R, Volume MINMAX, adaptive moving average _5

In [21]:
TechIndicator = copy.deepcopy(data)

##### <font color='red'>RSI(Relative Strength index)</font>
* 주식, 선물, 옵션 등의 기술적분석에 사용되는 보죠지표임.
* 상대강도지수라고 부르며, 가격의 상승압력과 하락입력간의 상대적인 강도를 나타내는 지표임
    : 즉 RSI는 주가의 상승추세와 비례하며, <font color = 'blue'>하단과 같이 구체적인 공식에 근거해 해석</font>

* U = 전날 주가보다 오늘 주가가 상승할 때의 주가 상승폭
* D = 전날 주가보다 오늘 주가가 하락할 때의 주가 상승폭
* AU = 일정기간(n)일 동안의 U의 평균값(Average ups)
* AD = 일정기간(n)일 동안의 D의 평균값(Average down)
* RS = AU/AD
* RSI = AU/(AU+AD) = RS/(1+RS)
```
Avg(PriceUp)/(Avg(PriceUP)+Avg(PriceDown)*100 
Where: PriceUp(t)=1*(Price(t)-Price(t-1)){Price(t)- Price(t-1)>0}
PriceDown(t)=-1*(Price(t)-Price(t-1)){Price(t)- Price(t-1)<0}
```

* RSI 시그널 = RSI의 이동평균선


###### 0과 1사이의 값으로 Scaling 및 AU가 클수록 RSI는 1로 수렴 / AD가 클수록 0으로 수렴 _1
###### N은 사용자가 임의로 정할 수 있는 파라미터 통산적으론 14일을 기준으로 책정 _2
###### RSI의 SIGNAL은 이동평균선이며, 6일 동안의 이동평균을 사용함 _3

In [22]:
# RSI 사용자정의함수 생성

# 0보다 큰 값과 작은 값의 절대값의 평균을 통해 각. AU, AD값을 정의 및 
# AU/(AU+AD) 즉, RSI의 백분위 수 출력
def rsi(values):
    up = values[values>0].mean()
    down = -1*values[values<0].mean()
    return 100 * up / (up + down)

In [23]:
# Momentum_1D >> 장 마감가를 기준으로 전날대비 가격차를 계산
# RSI_14D >> 14일을 기준으로 rolling하여 Rsi의 백분위 수 게산
# Volume_plain >> 결측값 0으로 처리 >> 정보가 기록되지 않은 것이라 가정햇기 때문일 것
for stock in range(len(TechIndicator)):
    TechIndicator[stock]['Momentum_1D'] = (TechIndicator[stock]['Close']-TechIndicator[stock]['Close'].shift(1)).fillna(0)
    TechIndicator[stock]['RSI_14D'] = TechIndicator[stock]['Momentum_1D'].rolling(center=False, window=14).apply(rsi).fillna(0)
    TechIndicator[stock]['Volume_plain'] = TechIndicator[stock]['Volume'].fillna(0)
TechIndicator[0].tail(5)

,Date,Open,High,Low,Close,Volume,OpenInt,Label,Momentum_1D,RSI_14D,Volume_plain
9037,2017-11-06,13.11,13.13,12.49,12.65,5909711,0,thc,-0.43,43.537415,5909711
9038,2017-11-07,13.28,13.88,12.78,13.21,7041401,0,thc,0.56,44.479495,7041401
9039,2017-11-08,13.22,13.68,12.91,13.63,3133643,0,thc,0.42,44.740973,3133643
9040,2017-11-09,13.18,13.54,13.04,13.50,1942268,0,thc,-0.13,40.553746,1942268
9041,2017-11-10,13.50,13.96,13.50,13.82,3128427,0,thc,0.32,43.234837,3128427

##### Bollinger Bands in python참고자료 : https://codingandfun.com/bollinger-bands-pyt/
##### Bollinger Bands 주식 용어 및 수식 참고자료 : 
https://m.blog.naver.com/PostView.nhn?blogId=kks3285&logNo=221229220122&proxyReferer=https:%2F%2Fwww.google.com%2F

* 주가의 상대적 높고 낮음에 대한 판단 목적의 기술적 분석도구
* 이동평균선 중심으로 표준편차 범위 안에서 움직인다

###### 구성
* 중심선 : n일 동안의 이동평균선
* 상단선 : 중심선 + k배 표준편차 상위밴드
* 하단선 : 중심선 + k배 표준편차 하위밴드
통상 n=20,k=2
###### <font color='red'>Bolinger Bands Formulas</font>
* mbb = 중심선 = 주가의 20 기간 이동평균선 = clo20
* ubb = 상한선 = 중심선 + 주가의 20기간 표준편차 * 2
* lbb = 하한선 = 중심선 – 주가의 20기간 표준편차 * 2
* perb = %b = (주가 – 하한선) / (상한선 – 하한선) = (close - lbb) / (ubb - lbb)
* bw = 밴드폭 (Bandwidth) = (상한선 – 하한선) / 중심선 = (ubb - lbb) / mbb

In [24]:
# Bolinger Band 사용자정의함수 생성
# '평균(average)'과 '표준편차(standard deviation)' return 상한, 하한값 
def bbands(price, length=30, numsd=2):
    ave = price.rolling(window = length, center = False).mean()
    sd = price.rolling(window = length, center = False).std()
    
    upband = ave + (sd*numsd)
    dnband = ave - (sd*numsd)
    return np.round(ave,3), np.round(upband,3), np.round(dnband,3)

In [28]:
# 장 마감 price, length = 20, n = 1 일 때, 
# ave = 'Bolinger Middle Band'
# upband = 'Bolinger Uper Band'
# dnband = 'Bolinger Lower Band' (Nan = 0)

for stock in range(len(TechIndicator)):
    TechIndicator[stock]['BB_Middle_Band'], TechIndicator[stock]['BB_Upper_Band'], TechIndicator[stock]['BB_Lower_Band'] = bbands(TechIndicator[stock]['Close'], length=20, numsd=1)
    TechIndicator[stock]['BB_Middle_Band'] = TechIndicator[stock]['BB_Middle_Band'].fillna(0)
    TechIndicator[stock]['BB_Upper_Band'] = TechIndicator[stock]['BB_Upper_Band'].fillna(0)
    TechIndicator[stock]['BB_Lower_Band'] = TechIndicator[stock]['BB_Lower_Band'].fillna(0)
TechIndicator[0].tail()

,Date,Open,High,Low,Close,Volume,OpenInt,Label,Momentum_1D,RSI_14D,Volume_plain,BB_Middle_Band,BB_Upper_Band,BB_Lower_Band
9037,2017-11-06,13.11,13.13,12.49,12.65,5909711,0,thc,-0.43,43.537415,5909711,13.742,14.401,13.083
9038,2017-11-07,13.28,13.88,12.78,13.21,7041401,0,thc,0.56,44.479495,7041401,13.682,14.333,13.032
9039,2017-11-08,13.22,13.68,12.91,13.63,3133643,0,thc,0.42,44.740973,3133643,13.639,14.260,13.018
9040,2017-11-09,13.18,13.54,13.04,13.50,1942268,0,thc,-0.13,40.553746,1942268,13.621,14.241,13.001
9041,2017-11-10,13.50,13.96,13.50,13.82,3128427,0,thc,0.32,43.234837,3128427,13.654,14.266,13.043

##### Aroon Oscillator참고자료 : http://blog.naver.com/PostView.nhn?blogId=ntkor&logNo=200061827#:~:text=Aroon%20Oscillator&text=%2D100%20~%20100%20%EC%82%AC%EC%9D%B4%EC%9D%98%20%EA%B0%92,%EC%9C%BC%EB%A1%9C%20%EC%A7%84%EB%8F%99%ED%95%98%EB%8A%94%20%EA%B7%B8%EB%9E%98%ED%94%84%20%EC%9D%B4%EB%8B%A4.

###### 구성
* Aroon Up, Aroon Down  
    * Aroon Up = ((N - Days since N - period High)/N) * 100
    * Aroon Down = ((N - Days since N - period Low)/N) * 100
 
###### 지표해석 _1
* 이 지표는 0 ~ 100사이 값을 가지고 위 아래로 움직이며, 25구간을 기본값으로 함
* 가장 기본적인 해석은 Aroon-Up이 50보다 크고 Aroon-Down이 50보다 작을 때는 상승세가 우세
* 각각이 50보다 작거나, 50보다 클 결우 하락세를 의심한다.

###### 지표해석 _2
* <font color='red'>Aroon Up / Down 지표가 100으로 접근한다는 것은 새로운 추세가 나타날 가능성이 높음 </font>
    * Ex)_ 반대 지표가 30 이하에 머물면 추세 발생 확률이 좀더 높은 것으로 볼 수 있음 (Up100 Down 30, 상승세가 발생할 확률이 높음)

In [38]:
# Testcode
# ((TechIndicator[0]['High'][0:25].tolist().index(max(TechIndicator[0]['High'][0:25]))))/float(25)*100

25.0

In [54]:
def aroon(df, tf=25):
    aroonup = []
    aroondown = []
    x = tf
    while x< len(df['Date']):
        aroon_up = ((df['High'][x-tf:x].tolist().index(max(df['High'][x-tf:x])))/float(tf))*100
        aroon_down = ((df['Low'][x-tf:x].tolist().index(min(df['Low'][x-tf:x])))/float(tf))*100
        aroonup.append(aroon_up)
        aroondown.append(aroon_down)
        x+=1
    return aroonup, aroondown

In [55]:
for stock in range(len(TechIndicator)):
    listofzeros = [0] * 25
    up, down = aroon(TechIndicator[stock])
    aroon_list = [x - y for x, y in zip(up,down)]
    if len(aroon_list)==0:
        aroon_list = [0] * TechIndicator[stock].shape[0]
        TechIndicator[stock]['Aroon_Oscillator'] = aroon_list
    else:
        TechIndicator[stock]['Aroon_Oscillator'] = listofzeros+aroon_list
TechIndicator[0]['Aroon_Oscillator'].tail(10)

9032   -36.0
9033   -36.0
9034   -36.0
9035   -36.0
9036   -36.0
9037   -36.0
9038   -32.0
9039   -28.0
9040   -20.0
9041   -20.0
Name: Aroon_Oscillator, dtype: float64

###### PVT(Price Volume Trend) = {(단일종가 - 전일종가) / 전일종가} * 단일거래량 + 전일PVT
* 참고자료 : https://layhope.tistory.com/495

In [56]:
for stock in range(len(TechIndicator)):
    TechIndicator[stock]["PVT"] = (TechIndicator[stock]['Momentum_1D']/ TechIndicator[stock]['Close'].shift(1))*TechIndicator[stock]['Volume']
    TechIndicator[stock]["PVT"] = TechIndicator[stock]["PVT"]-TechIndicator[stock]["PVT"].shift(1)
    TechIndicator[stock]["PVT"] = TechIndicator[stock]["PVT"].fillna(0)
TechIndicator[0].tail()

,Date,Open,High,Low,Close,Volume,OpenInt,Label,Momentum_1D,RSI_14D,Volume_plain,BB_Middle_Band,BB_Upper_Band,BB_Lower_Band,Aroon_Oscillator,PVT
9037,2017-11-06,13.11,13.13,12.49,12.65,5909711,0,thc,-0.43,43.537415,5909711,13.742,14.401,13.083,-36.0,49157.900112
9038,2017-11-07,13.28,13.88,12.78,13.21,7041401,0,thc,0.56,44.479495,7041401,13.682,14.333,13.032,-32.0,505993.684528
9039,2017-11-08,13.22,13.68,12.91,13.63,3133643,0,thc,0.42,44.740973,3133643,13.639,14.260,13.018,-28.0,-212082.850030
9040,2017-11-09,13.18,13.54,13.04,13.50,1942268,0,thc,-0.13,40.553746,1942268,13.621,14.241,13.001,-20.0,-118156.277672
9041,2017-11-10,13.50,13.96,13.50,13.82,3128427,0,thc,0.32,43.234837,3128427,13.654,14.266,13.043,-20.0,92680.239902

###### Acceleration Bands

In [57]:
def abands(df):
    df['AB_Middle_Band'] = df['Close'].rolling(window = 20, center=False).mean()
    df['aupband'] = df['High'] * (1 + 4 * (df['High']-df['Low'])/(df['High']+df['Low']))
    df['AB_Upper_Band'] = df['aupband'].rolling(window=20, center=False).mean()
    df['adownband'] = df['Low'] * (1 - 4 * (df['High']-df['Low'])/(df['High']+df['Low']))
    df['AB_Lower_Band'] = df['adownband'].rolling(window=20, center=False).mean()

In [58]:
for stock in range(len(TechIndicator)):
    abands(TechIndicator[stock])
    TechIndicator[stock] = TechIndicator[stock].fillna(0)
TechIndicator[0].tail()

,Date,Open,High,Low,Close,Volume,OpenInt,Label,Momentum_1D,RSI_14D,...,BB_Middle_Band,BB_Upper_Band,BB_Lower_Band,Aroon_Oscillator,PVT,AB_Middle_Band,aupband,AB_Upper_Band,adownband,AB_Lower_Band
9037,2017-11-06,13.11,13.13,12.49,12.65,5909711,0,thc,-0.43,43.537415,...,13.742,14.401,13.083,-36.0,49157.900112,13.7420,14.441975,15.915641,11.241975,11.786191
9038,2017-11-07,13.28,13.88,12.78,13.21,7041401,0,thc,0.56,44.479495,...,13.682,14.333,13.032,-32.0,505993.684528,13.6825,16.170773,15.903654,10.670773,11.666704
9039,2017-11-08,13.22,13.68,12.91,13.63,3133643,0,thc,0.42,44.740973,...,13.639,14.260,13.018,-28.0,-212082.850030,13.6390,15.264596,15.869959,11.414596,11.570509
9040,2017-11-09,13.18,13.54,13.04,13.50,1942268,0,thc,-0.13,40.553746,...,13.621,14.241,13.001,-20.0,-118156.277672,13.6210,14.558811,15.808294,12.058811,11.543294
9041,2017-11-10,13.50,13.96,13.50,13.82,3128427,0,thc,0.32,43.234837,...,13.654,14.266,13.043,-20.0,92680.239902,13.6545,14.895412,15.748591,12.595412,11.678591

In [65]:
# Drop unwanted columns
colums2Drop = ['Momentum_1D','aupband','adownband']
for stock in range(len(TechIndicator)):
    TechIndicator[stock] = TechIndicator[stock].drop(labels = colums2Drop, axis=1)
TechIndicator[0].tail(5)

,Date,Open,High,Low,Close,Volume,OpenInt,Label,RSI_14D,Volume_plain,BB_Middle_Band,BB_Upper_Band,BB_Lower_Band,Aroon_Oscillator,PVT,AB_Middle_Band,AB_Upper_Band,AB_Lower_Band
9037,2017-11-06,13.11,13.13,12.49,12.65,5909711,0,thc,43.537415,5909711,13.742,14.401,13.083,-36.0,49157.900112,13.7420,15.915641,11.786191
9038,2017-11-07,13.28,13.88,12.78,13.21,7041401,0,thc,44.479495,7041401,13.682,14.333,13.032,-32.0,505993.684528,13.6825,15.903654,11.666704
9039,2017-11-08,13.22,13.68,12.91,13.63,3133643,0,thc,44.740973,3133643,13.639,14.260,13.018,-28.0,-212082.850030,13.6390,15.869959,11.570509
9040,2017-11-09,13.18,13.54,13.04,13.50,1942268,0,thc,40.553746,1942268,13.621,14.241,13.001,-20.0,-118156.277672,13.6210,15.808294,11.543294
9041,2017-11-10,13.50,13.96,13.50,13.82,3128427,0,thc,43.234837,3128427,13.654,14.266,13.043,-20.0,92680.239902,13.6545,15.748591,11.678591

###### Stochastic Oscillator(%K and %D)

In [66]:
def STOK(df, n):
    df['STOK'] = ((df['Close'] - df['Low'].rolling(window=n, center=False).mean()) / (df['High'].rolling(window=n, center=False).max() - df['Low'].rolling(window=n, center=False).min())) * 100
    df['STOD'] = df['STOK'].rolling(window = 3, center=False).mean()

In [67]:
for stock in range(len(TechIndicator)):
    STOK(TechIndicator[stock], 4)
    TechIndicator[stock] = TechIndicator[stock].fillna(0)
TechIndicator[0].tail()

,Date,Open,High,Low,Close,Volume,OpenInt,Label,RSI_14D,Volume_plain,BB_Middle_Band,BB_Upper_Band,BB_Lower_Band,Aroon_Oscillator,PVT,AB_Middle_Band,AB_Upper_Band,AB_Lower_Band,STOK,STOD
9037,2017-11-06,13.11,13.13,12.49,12.65,5909711,0,thc,43.537415,5909711,13.742,14.401,13.083,-36.0,49157.900112,13.7420,15.915641,11.786191,-31.516588,-18.649986
9038,2017-11-07,13.28,13.88,12.78,13.21,7041401,0,thc,44.479495,7041401,13.682,14.333,13.032,-32.0,505993.684528,13.6825,15.903654,11.666704,8.293839,-20.078579
9039,2017-11-08,13.22,13.68,12.91,13.63,3133643,0,thc,44.740973,3133643,13.639,14.260,13.018,-28.0,-212082.850030,13.6390,15.869959,11.570509,56.551724,11.109658
9040,2017-11-09,13.18,13.54,13.04,13.50,1942268,0,thc,40.553746,1942268,13.621,14.241,13.001,-20.0,-118156.277672,13.6210,15.808294,11.543294,50.000000,38.281854
9041,2017-11-10,13.50,13.96,13.50,13.82,3128427,0,thc,43.234837,3128427,13.654,14.266,13.043,-20.0,92680.239902,13.6545,15.748591,11.678591,64.618644,57.056789

###### Chaikin Money Flow

* 참고자료 : https://blog.naver.com/PostView.nhn?blogId=autumnis&logNo=222057485370
    * Sum((((C-L)-(H-L))/(H-L))*V, time) / Sum(V, time),  Time = 21 - 22구간
            * C : Center
            * L : Low
            * H : High
            * V : Volumn
: 매우 단순한 접근에 해당한다. 유도된 식을 풀이해보자면 변동폭에서 중앙부터 상한선까지 Volume값을 기준단위로하여 상승빈도가 유동 range 안에서 얼마 만큼 점유하고 있는지를 (약 20ㅇ르 주기로 ) 평가하는 지표이다.

: 주가 해석에서 모든 값은 상대적인 값이다.
위와 같은 CMF가 유용할 수 있는 것은 주가가 하락세를 보이더라도 상대적 하락세이며 본질적으론 상승세인 것을 판단할 수 있도록 돕는다.

이와 같은 특징을 고려했을 때, 상관분석을 통해 주가 상승세를 기준으로 양의 상관관계, 하락세를 기준으로 음의 상관관계를 판별하여 Feature를 특정짓고 Efficient frontier 포트폴리오를 만든다면 어떨까를 고려해본다.

In [69]:
def CMFlow(df, tf):
    CHMF = []
    MFMs = []
    MFVs = []
    x = tf
    
    while x < len(df['Date']):
        PeriodVolume = 0
        volRange = df['Volume'][x-tf:x]
        for eachVol in volRange:
            PeriodVolume += eachVol
        
        MFM = ((df['Close'][x] - df['Low'][x]) - (df['High'][x] - df['Close'][x])) / (df['High'][x] - df['Low'][x])
        MFV = MFM*PeriodVolume
        
        MFMs.append(MFM)
        MFVs.append(MFV)
        x+=1
    
    y = tf
    while y < len(MFVs):
        PeriodVolume = 0
        volRange = df['Volume'][x-tf:x]
        for eachVol in volRange:
            PeriodVolume += eachVol
        consider = MFVs[y-tf:y]
        tfsMFV = 0
        
        for eachMFV in consider:
            tfsMFV += eachMFV
        
        tfsCMF = tfsMFV/PeriodVolume
        CHMF.append(tfsCMF)
        y+=1
    return CHMF

In [70]:
for stock in range(len(TechIndicator)):
    listofzeros = [0] * 40
    CHMF = CMFlow(TechIndicator[stock], 20)
    if len(CHMF)==0:
        CHMF = [0] * TechIndicator[stock].shape[0]
        TechIndicator[stock]['Chaikin_MF'] = CHMF
    else:
        TechIndicator[stock]['Chaikin_MF'] = listofzeros+CHMF
TechIndicator[0].tail()

<ipython-input-69-ebdd63a3bbec>:13: RuntimeWarning: invalid value encountered in double_scalars
  MFM = ((df['Close'][x] - df['Low'][x]) - (df['High'][x] - df['Close'][x])) / (df['High'][x] - df['Low'][x])

,Date,Open,High,Low,Close,Volume,OpenInt,Label,RSI_14D,Volume_plain,...,BB_Upper_Band,BB_Lower_Band,Aroon_Oscillator,PVT,AB_Middle_Band,AB_Upper_Band,AB_Lower_Band,STOK,STOD,Chaikin_MF
9037,2017-11-06,13.11,13.13,12.49,12.65,5909711,0,thc,43.537415,5909711,...,14.401,13.083,-36.0,49157.900112,13.7420,15.915641,11.786191,-31.516588,-18.649986,-1.701634
9038,2017-11-07,13.28,13.88,12.78,13.21,7041401,0,thc,44.479495,7041401,...,14.333,13.032,-32.0,505993.684528,13.6825,15.903654,11.666704,8.293839,-20.078579,-1.684573
9039,2017-11-08,13.22,13.68,12.91,13.63,3133643,0,thc,44.740973,3133643,...,14.260,13.018,-28.0,-212082.850030,13.6390,15.869959,11.570509,56.551724,11.109658,-1.156788
9040,2017-11-09,13.18,13.54,13.04,13.50,1942268,0,thc,40.553746,1942268,...,14.241,13.001,-20.0,-118156.277672,13.6210,15.808294,11.543294,50.000000,38.281854,0.110604
9041,2017-11-10,13.50,13.96,13.50,13.82,3128427,0,thc,43.234837,3128427,...,14.266,13.043,-20.0,92680.239902,13.6545,15.748591,11.678591,64.618644,57.056789,1.700392

###### SAR = SAR + {AF * (EP - SAR)}
* 추세전환시점을 파악할 목적으로 개발된 지표
* Parablic stop And Reverse은 주가의 추세의 끝과 시작을 점들의 포물선으로 차트에 표시해 알려주는데, 이러한 추세의 포물선의 표시 원리는 추세진행의 가속력에 착안하여 개발되어졌다. 주식은 추세가 형성되어 움직일 때 가속력이 높아지며, 추세가 전환되는 시점에는 가속력이 약해지는 특성을 활용한 것이다.

In [71]:
def psar(df, iaf = 0.02, maxaf = 0.2):
    length = len(df)
    dates = (df['Date'])
    high = (df['High'])
    low = (df['Low'])
    close = (df['Close'])
    psar = df['Close'][0:len(df['Close'])]
    psarbull = [None] * length
    psarbear = [None] * length
    bull = True
    af = iaf
    ep = df['Low'][0]
    hp = df['High'][0]
    lp = df['Low'][0]
    for i in range(2,length):
        if bull:
            psar[i] = psar[i - 1] + af * (hp - psar[i - 1])
        else:
            psar[i] = psar[i - 1] + af * (lp - psar[i - 1])
        reverse = False
        if bull:
            if df['Low'][i] < psar[i]:
                bull = False
                reverse = True
                psar[i] = hp
                lp = df['Low'][i]
                af = iaf
        else:
            if df['High'][i] > psar[i]:
                bull = True
                reverse = True
                psar[i] = lp
                hp = df['High'][i]
                af = iaf
        if not reverse:
            if bull:
                if df['High'][i] > hp:
                    hp = df['High'][i]
                    af = min(af + iaf, maxaf)
                if df['Low'][i - 1] < psar[i]:
                    psar[i] = df['Low'][i - 1]
                if df['Low'][i - 2] < psar[i]:
                    psar[i] = df['Low'][i - 2]
            else:
                if df['Low'][i] < lp:
                    lp = df['Low'][i]
                    af = min(af + iaf, maxaf)
                if df['High'][i - 1] > psar[i]:
                    psar[i] = df['High'][i - 1]
                if df['High'][i - 2] > psar[i]:
                    psar[i] = df['High'][i - 2]
        if bull:
            psarbull[i] = psar[i]
        else:
            psarbear[i] = psar[i]
    df['psar'] = psar

In [72]:
for stock in range(len(TechIndicator)):
    psar(TechIndicator[stock])

TechIndicator[0].tail()

,Date,Open,High,Low,Close,Volume,OpenInt,Label,RSI_14D,Volume_plain,...,BB_Lower_Band,Aroon_Oscillator,PVT,AB_Middle_Band,AB_Upper_Band,AB_Lower_Band,STOK,STOD,Chaikin_MF,psar
9037,2017-11-06,13.11,13.13,12.49,14.960000,5909711,0,thc,43.537415,5909711,...,13.083,-36.0,49157.900112,13.7420,15.915641,11.786191,-31.516588,-18.649986,-1.701634,14.960000
9038,2017-11-07,13.28,13.88,12.78,14.910600,7041401,0,thc,44.479495,7041401,...,13.032,-32.0,505993.684528,13.6825,15.903654,11.666704,8.293839,-20.078579,-1.684573,14.910600
9039,2017-11-08,13.22,13.68,12.91,14.862188,3133643,0,thc,44.740973,3133643,...,13.018,-28.0,-212082.850030,13.6390,15.869959,11.570509,56.551724,11.109658,-1.156788,14.862188
9040,2017-11-09,13.18,13.54,13.04,14.814744,1942268,0,thc,40.553746,1942268,...,13.001,-20.0,-118156.277672,13.6210,15.808294,11.543294,50.000000,38.281854,0.110604,14.814744
9041,2017-11-10,13.50,13.96,13.50,14.768249,3128427,0,thc,43.234837,3128427,...,13.043,-20.0,92680.239902,13.6545,15.748591,11.678591,64.618644,57.056789,1.700392,14.768249

###### Price Rate of Change
* ROC = [(Close - Close n periods ago) / (Close n periods ago)] * 100

In [74]:
for stock in range(len(TechIndicator)):
    TechIndicator[stock]['ROC'] = ((TechIndicator[stock]['Close'] - TechIndicator[stock]['Close'].shift(12))/(TechIndicator[stock]['Close'].shift(12)))*100
    TechIndicator[stock] = TechIndicator[stock].fillna(0)
TechIndicator[0].tail()

,Date,Open,High,Low,Close,Volume,OpenInt,Label,RSI_14D,Volume_plain,...,Aroon_Oscillator,PVT,AB_Middle_Band,AB_Upper_Band,AB_Lower_Band,STOK,STOD,Chaikin_MF,psar,ROC
9037,2017-11-06,13.11,13.13,12.49,14.960000,5909711,0,thc,43.537415,5909711,...,-36.0,49157.900112,13.7420,15.915641,11.786191,-31.516588,-18.649986,-1.701634,14.960000,-0.127941
9038,2017-11-07,13.28,13.88,12.78,14.910600,7041401,0,thc,44.479495,7041401,...,-32.0,505993.684528,13.6825,15.903654,11.666704,8.293839,-20.078579,-1.684573,14.910600,1.389559
9039,2017-11-08,13.22,13.68,12.91,14.862188,3133643,0,thc,44.740973,3133643,...,-28.0,-212082.850030,13.6390,15.869959,11.570509,56.551724,11.109658,-1.156788,14.862188,21.323984
9040,2017-11-09,13.18,13.54,13.04,14.814744,1942268,0,thc,40.553746,1942268,...,-20.0,-118156.277672,13.6210,15.808294,11.543294,50.000000,38.281854,0.110604,14.814744,20.403962
9041,2017-11-10,13.50,13.96,13.50,14.768249,3128427,0,thc,43.234837,3128427,...,-20.0,92680.239902,13.6545,15.748591,11.678591,64.618644,57.056789,1.700392,14.768249,19.510170

###### Calculation of Volume Weighted Average Price

In [75]:
for stock in range(len(TechIndicator)):
    TechIndicator[stock]['VWAP'] = np.cumsum(TechIndicator[stock]['Volume'] * (TechIndicator[stock]['High'] + TechIndicator[stock]['Low'])/2) / np.cumsum(TechIndicator[stock]['Volume'])
    TechIndicator[stock] = TechIndicator[stock].fillna(0)
TechIndicator[0].tail()

,Date,Open,High,Low,Close,Volume,OpenInt,Label,RSI_14D,Volume_plain,...,PVT,AB_Middle_Band,AB_Upper_Band,AB_Lower_Band,STOK,STOD,Chaikin_MF,psar,ROC,VWAP
9037,2017-11-06,13.11,13.13,12.49,14.960000,5909711,0,thc,43.537415,5909711,...,49157.900112,13.7420,15.915641,11.786191,-31.516588,-18.649986,-1.701634,14.960000,-0.127941,37.401608
9038,2017-11-07,13.28,13.88,12.78,14.910600,7041401,0,thc,44.479495,7041401,...,505993.684528,13.6825,15.903654,11.666704,8.293839,-20.078579,-1.684573,14.910600,1.389559,37.382744
9039,2017-11-08,13.22,13.68,12.91,14.862188,3133643,0,thc,44.740973,3133643,...,-212082.850030,13.6390,15.869959,11.570509,56.551724,11.109658,-1.156788,14.862188,21.323984,37.374346
9040,2017-11-09,13.18,13.54,13.04,14.814744,1942268,0,thc,40.553746,1942268,...,-118156.277672,13.6210,15.808294,11.543294,50.000000,38.281854,0.110604,14.814744,20.403962,37.369142
9041,2017-11-10,13.50,13.96,13.50,14.768249,3128427,0,thc,43.234837,3128427,...,92680.239902,13.6545,15.748591,11.678591,64.618644,57.056789,1.700392,14.768249,19.510170,37.360919

###### Calculation of Momentum

In [76]:
for stock in range(len(TechIndicator)):
    TechIndicator[stock]['Momentum'] = TechIndicator[stock]['Close'] - TechIndicator[stock]['Close'].shift(4)
    TechIndicator[stock] = TechIndicator[stock].fillna(0)
TechIndicator[0].tail()

,Date,Open,High,Low,Close,Volume,OpenInt,Label,RSI_14D,Volume_plain,...,AB_Middle_Band,AB_Upper_Band,AB_Lower_Band,STOK,STOD,Chaikin_MF,psar,ROC,VWAP,Momentum
9037,2017-11-06,13.11,13.13,12.49,14.960000,5909711,0,thc,43.537415,5909711,...,13.7420,15.915641,11.786191,-31.516588,-18.649986,-1.701634,14.960000,-0.127941,37.401608,2.400633
9038,2017-11-07,13.28,13.88,12.78,14.910600,7041401,0,thc,44.479495,7041401,...,13.6825,15.903654,11.666704,8.293839,-20.078579,-1.684573,14.910600,1.389559,37.382744,2.303220
9039,2017-11-08,13.22,13.68,12.91,14.862188,3133643,0,thc,44.740973,3133643,...,13.6390,15.869959,11.570509,56.551724,11.109658,-1.156788,14.862188,21.323984,37.374346,2.207756
9040,2017-11-09,13.18,13.54,13.04,14.814744,1942268,0,thc,40.553746,1942268,...,13.6210,15.808294,11.543294,50.000000,38.281854,0.110604,14.814744,20.403962,37.369142,2.114201
9041,2017-11-10,13.50,13.96,13.50,14.768249,3128427,0,thc,43.234837,3128427,...,13.6545,15.748591,11.678591,64.618644,57.056789,1.700392,14.768249,19.510170,37.360919,-0.191751

###### Commodity Channel Index

In [77]:
def CCI(df, n, constant):
    TP = (df['High'] + df['Low'] + df['Close']) / 3
    CCI = pd.Series((TP - TP.rolling(window=n, center=False).mean()) / (constant * TP.rolling(window=n, center=False).std())) #, name = 'CCI_' + str(n))
    return CCI

In [78]:
for stock in range(len(TechIndicator)):
    TechIndicator[stock]['CCI'] = CCI(TechIndicator[stock], 20, 0.015)
    TechIndicator[stock] = TechIndicator[stock].fillna(0)
TechIndicator[0].tail()

,Date,Open,High,Low,Close,Volume,OpenInt,Label,RSI_14D,Volume_plain,...,AB_Upper_Band,AB_Lower_Band,STOK,STOD,Chaikin_MF,psar,ROC,VWAP,Momentum,CCI
9037,2017-11-06,13.11,13.13,12.49,14.960000,5909711,0,thc,43.537415,5909711,...,15.915641,11.786191,-31.516588,-18.649986,-1.701634,14.960000,-0.127941,37.401608,2.400633,-39.398601
9038,2017-11-07,13.28,13.88,12.78,14.910600,7041401,0,thc,44.479495,7041401,...,15.903654,11.666704,8.293839,-20.078579,-1.684573,14.910600,1.389559,37.382744,2.303220,2.872147
9039,2017-11-08,13.22,13.68,12.91,14.862188,3133643,0,thc,44.740973,3133643,...,15.869959,11.570509,56.551724,11.109658,-1.156788,14.862188,21.323984,37.374346,2.207756,9.658417
9040,2017-11-09,13.18,13.54,13.04,14.814744,1942268,0,thc,40.553746,1942268,...,15.808294,11.543294,50.000000,38.281854,0.110604,14.814744,20.403962,37.369142,2.114201,22.527712
9041,2017-11-10,13.50,13.96,13.50,14.768249,3128427,0,thc,43.234837,3128427,...,15.748591,11.678591,64.618644,57.056789,1.700392,14.768249,19.510170,37.360919,-0.191751,84.001824